name: "CI – Cypress Component Tests"

on:
  pull_request:
    branches:
      - develop

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install client dependencies
        run: |
          cd Develop/client
          npm install

      - name: Start client dev server
        run: |
          cd Develop/client
          npm run dev -- --port 5173 &

      - name: Wait for dev server
        run: npx wait-on http://localhost:5173

      - name: Run Cypress component tests
        run: |
          cd Develop
          npx cypress run --component --config-file cypress.config.ts
